language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install flake8
  - python setup.py bdist_wheel
  - pip install dist/feedgen*

script:
  - make test
  - python -m feedgen
  - python -m feedgen atom
  - python -m feedgen rss
